config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  devise_for :users
  resources :qualifications
  resources :vehicles
  resources :users
  resources :routes
  resources :domains
  resources :companies
  root :to => "home#index" 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/qualification.rb
class Qualification < ApplicationRecord
  belongs_to :user
end

app/controllers/qualifications_controller.rb
class QualificationsController < ApplicationController
  before_action :set_qualification, only: [:show, :edit, :update, :destroy]

  # GET /qualifications
  # GET /qualifications.json
  def index
    @qualifications = Qualification.all
  end

  # GET /qualifications/1
  # GET /qualifications/1.json
  def show
  end

  # GET /qualifications/new
  def new
    @qualification = Qualification.new
  end

  # GET /qualifications/1/edit
  def edit
  end

  # POST /qualifications
  # POST /qualifications.json
  def create
    @qualification = Qualification.new(qualification_params)

    respond_to do |format|
      if @qualification.save
        format.html { redirect_to @qualification, notice: 'Qualification was successfully created.' }
        format.json { render :show, status: :created, location: @qualification }
      else
        format.html { render :new }
        format.json { render json: @qualification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /qualifications/1
  # PATCH/PUT /qualifications/1.json
  def update
    respond_to do |format|
      if @qualification.update(qualification_params)
        format.html { redirect_to @qualification, notice: 'Qualification was successfully updated.' }
        format.json { render :show, status: :ok, location: @qualification }
      else
        format.html { render :edit }
        format.json { render json: @qualification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /qualifications/1
  # DELETE /qualifications/1.json
  def destroy
    @qualification.destroy
    respond_to do |format|
      format.html { redirect_to qualifications_url, notice: 'Qualification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_qualification
      @qualification = Qualification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def qualification_params
      params.require(:qualification).permit(:value_cal, :date_cal, :user_id)
    end
end

app/helpers/qualifications_helper.rb
module QualificationsHelper
end

app/views/qualifications/_form.html.erb
<%= form_with(model: qualification, local: true) do |form| %>
  <% if qualification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(qualification.errors.count, "error") %> prohibited this qualification from being saved:</h2>

      <ul>
      <% qualification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :value_cal %>
    <%= form.number_field :value_cal, id: :qualification_value_cal %>
  </div>

  <div class="field">
    <%= form.label :date_cal %>
    <%= form.date_select :date_cal, id: :qualification_date_cal %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :qualification_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/qualifications/edit.html.erb
<h1>Editing Qualification</h1>

<%= render 'form', qualification: @qualification %>

<%= link_to 'Show', @qualification %> |
<%= link_to 'Back', qualifications_path %>

app/views/qualifications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Qualifications</h1>

<table>
  <thead>
    <tr>
      <th>Value cal</th>
      <th>Date cal</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @qualifications.each do |qualification| %>
      <tr>
        <td><%= qualification.value_cal %></td>
        <td><%= qualification.date_cal %></td>
        <td><%= qualification.user %></td>
        <td><%= link_to 'Show', qualification %></td>
        <td><%= link_to 'Edit', edit_qualification_path(qualification) %></td>
        <td><%= link_to 'Destroy', qualification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Qualification', new_qualification_path %>

app/views/qualifications/new.html.erb
<h1>New Qualification</h1>

<%= render 'form', qualification: @qualification %>

<%= link_to 'Back', qualifications_path %>

app/views/qualifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Value cal:</strong>
  <%= @qualification.value_cal %>
</p>

<p>
  <strong>Date cal:</strong>
  <%= @qualification.date_cal %>
</p>

<p>
  <strong>User:</strong>
  <%= @qualification.user %>
</p>

<%= link_to 'Edit', edit_qualification_path(@qualification) %> |
<%= link_to 'Back', qualifications_path %>